cities:
  CityOne:
    name: 'Cartegenia De Indias'
    used: true
    warps:
    - ==: me.tigahz.bpcore.serializable.City
      name: Parroquia San Pedro Claver
      position: 1
      warpName: 'Cartegena:ParroquiaSanPedroClaver'
    - ==: me.tigahz.bpcore.serializable.City
      name: Monumento Torre Del Reloj
      position: 2
      warpName: 'Cartegena:MonumentoTorreDelReloj'
    - ==: me.tigahz.bpcore.serializable.City
      name: Parque De La Marina
      position: 3
      warpName: 'Cartegena:ParqueDeLaMarina'
    - ==: me.tigahz.bpcore.serializable.City
      name: Plaza De Bolivar
      position: 4
      warpName: 'Cartegena:PlazaDeBolivar'
    - ==: me.tigahz.bpcore.serializable.City
      name: Plaza De La Aduana
      position: 5
      warpName: 'Cartegena:PlazaDeLaAduana'
  CityTwo:
    name: 'Argon'
    used: true
    warps:
    - ==: me.tigahz.bpcore.serializable.City
      name: Downtown Argon
      position: 1
      warpName: 'Argon:Downtown'
    - ==: me.tigahz.bpcore.serializable.City
      name: North Argon
      position: 2
      warpName: 'Argon:North'
    - ==: me.tigahz.bpcore.serializable.City
      name: Argon University
      position: 3
      warpName: 'Argon:University'
  CityThree:
    name: 'Hamilton'
    used: true
    warps:
    - ==: me.tigahz.bpcore.serializable.City
      name: Marshall
      position: 1
      warpName: 'Hamilton:Marshall'
    - ==: me.tigahz.bpcore.serializable.City
      name: Midtown
      position: 2
      warpName: 'Hamilton:Midtown'
    - ==: me.tigahz.bpcore.serializable.City
      name: Overlook
      position: 3
      warpName: 'Hamilton:Overlook'
    - ==: me.tigahz.bpcore.serializable.City
      name: Ridgewood
      position: 4
      warpName: 'Hamilton:Ridgewood'
    - ==: me.tigahz.bpcore.serializable.City
      name: Selwick
      position: 5
      warpName: 'Hamilton:Selwick'
    - ==: me.tigahz.bpcore.serializable.City
      name: Sublette Heights
      position: 6
      warpName: 'Hamilton:SubletteHeights'
  CityFour:
    name: 'Larimer'
    used: true
    warps:
    - ==: me.tigahz.bpcore.serializable.City
      name: Jefferson Point
      position: 1
      warpName: 'Larimer:JeffersonPoint'
  CityFive:
    name: 'NYC'
    used: true 
    warps:
    - ==: me.tigahz.bpcore.serializable.City
      name: Chinatown
      position: 1
      warpName: 'NYC:Chinatown'
    - ==: me.tigahz.bpcore.serializable.City
      name: Times Square
      position: 2
      warpName: 'NYC:TimesSquare'
    - ==: me.tigahz.bpcore.serializable.City
      name: Wall Street
      position: 3
      warpName: 'NYC:WallStreet'
    - ==: me.tigahz.bpcore.serializable.City
      name: WTC
      position: 4
      warpName: 'NYC:WTC'
  CitySix:
    name: 'Nations'
    used: true
    warps:
    - ==: me.tigahz.bpcore.serializable.City
      name: Alpenwald
      position: 1
      warpName: 'Nations:Alpenwald'
    - ==: me.tigahz.bpcore.serializable.City
      name: Avalon
      position: 2
      warpName: 'Nations:Avalon'
    - ==: me.tigahz.bpcore.serializable.City
      name: Borivia
      position: 3
      warpName: 'Nations:Borivia'
    - ==: me.tigahz.bpcore.serializable.City
      name: Canaydia
      position: 4
      warpName: 'Nations:Canaydia'
    - ==: me.tigahz.bpcore.serializable.City
      name: Dakota
      position: 5
      warpName: 'Nations:Dakota'
    - ==: me.tigahz.bpcore.serializable.City
      name: Escambia
      position: 6
      warpName: 'Nations:Escambia'
    - ==: me.tigahz.bpcore.serializable.City
      name: Hessen
      position: 7
      warpName: 'Nations:Hessen'
    - ==: me.tigahz.bpcore.serializable.City
      name: Mingtao
      position: 8
      warpName: 'Nations:Mingtao'
    - ==: me.tigahz.bpcore.serializable.City
      name: Nordterre
      position: 9
      warpName: 'Nations:Nordterre'
    - ==: me.tigahz.bpcore.serializable.City
      name: Ontario
      position: 10
      warpName: 'Nations:Ontario'
    - ==: me.tigahz.bpcore.serializable.City
      name: Ouesterre
      position: 11
      warpName: 'Nations:Ouesterre'
    - ==: me.tigahz.bpcore.serializable.City
      name: Tregnome
      position: 12
      warpName: 'Nations:Tregnome'
  CitySeven:
    name: ''
    used: false
    warps:
  CityEight:
    name: ''
    used: false
    warps:
  CityNine:
    name: ''
    used: false
    warps:
  CityTen:
    name: ''
    used: false
    warps:
  CityEleven:
    name: ''
    used: false
    warps:
  CityTwelve:
    name: ''
    used: false
    warps:
  CityThirteen:
    name: ''
    used: false
    warps:
  CityFourteen:
    name: ''
    used: false
    warps: