directors:
  - ==: me.tigahz.bpcore.rank.Director
    uuid: cd984ea6-afb6-4420-84a3-0a48c35ed017
    position: 1
    lore:
    - 'Ryer is the great'
  - ==: me.tigahz.bpcore.rank.Director
    uuid: d647a72b-a933-41fe-a620-e77b6c71f1c8
    position: 2
    lore:
    - 'Eh add what u want'
    - 'lmao'
  - ==: me.tigahz.bpcore.rank.Director
    uuid: 21e2492e-b7fa-4015-aa9c-999c46fdf838
    position: 3
    lore:
    - 'Pretty noice'
  - ==: me.tigahz.bpcore.rank.Director
    uuid: 37d35d3b-b635-4f02-b2c1-9b4c3d0cdf83
    position: 4
    lore:
    - 'Was never on IAS'
  - ==: me.tigahz.bpcore.rank.Director
    uuid: 6fd65c6b-8e27-47b1-ac53-59fdc2b6b8ac
    position: 5
    lore:
    - 'Ngl never seen him on'